# See https://alacritty.org/config-alacritty.html

import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[font]
size = 18

[font.normal]
family = "Hack Nerd Font Mono"

[window]
option_as_alt = "Both"

decorations = "Buttonless"
opacity = 0.90
blur = true

[window.padding]
x = 8
y = 0

[window.dimensions]
columns = 130
lines = 40

[cursor]
blink_interval = 400
blink_timeout = 0

[cursor.style]
shape = "Beam"
blinking = "Always"

[colors]
primary.background = "#001626" # blueish
# primary.background = "#222436" # grayish

[keyboard]
bindings = [
  { key = "F12", action = "ToggleSimpleFullscreen" }
]

[mouse]
hide_when_typing = true
