# See https://alacritty.org/config-alacritty.html

import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[font]
size = 18

[font.normal]
family = "Hack Nerd Font Mono"

[window]
decorations = "none"

[window.padding]
x = 8
y = 1

