# vim:set ft=tmux:
%hidden MODULE_NAME="demux"

set -ogq "@catppuccin_${MODULE_NAME}_icon" ""
set -ogqF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_blue}"
set -gq "@catppuccin_${MODULE_NAME}_text" " #(demux status)"

source -F "$HOME/.tmux/plugins/catppuccin/utils/status_module.conf"
