#!/bin/bash

# A bash script that helps me create notes
# Stolen from https://github.com/mischavandenburg/dotfiles with
# some personal touches

# function to prompt the user for a filename
get_filename() {
	read -p "Enter a filename: " filename
	echo "$filename"
}

# function to create the file, open Nvim in the $BRAIN folder and open the
# file to edit
open_file() {
	cd $BRAIN
	path="2-self"

	if [ ! -f "$path/$filename.md" ]; then
		touch "$path/$filename.md"

		file_id="$(date +"%Y%m%d%H%m")"
		timestamp="$(date +"%Y-%m-%d")"

		# File template
		{
			echo "---"
			echo "Created At: $timestamp"
			echo "Filename: $filename"
			echo "Resource: "
			echo "---"
			echo -en "\n"
			echo "# "
			echo -en "\n"
			echo -en "\n"
			echo -en "\n"
			echo "Links:"
			echo -en "\n"
			echo "$file_id"
		} >>"$path/$filename.md"
	fi

	nvim -c "e $path/$filename.md"
}

# Prompt the user if no filename is provided
if [[ $# -eq 0 ]]; then
	filename=$(get_filename)
fi

# if more than one argument is given, print error message and stop script
if [[ $# -gt 1 ]]; then
	echo "Please provide only one filename separated by dashes, without .md extension."
	echo "Example: zet my-new-note"
	exit 1
fi

# set filename to the argument given to the script
if [[ $# -eq 1 ]]; then
	filename=$1
fi

open_file
