#!/usr/bin/env bash

# W0
tmux rename-window -t 0 "Code"
tmux send-keys "nvim" Enter
tmux setw window-status-activity-style none

# W1
tmux new-window -n "Console"
tmux split-window -h
tmux setw window-status-activity-style none

# W2
tmux new-window -n "Git"
tmux send-keys "lazygit" Enter
tmux setw window-status-activity-style none

# W3
tmux new-window -n "PRs"
tmux send-keys "gh dash --config ~/.config/gh-dash/nuvos.yml" Enter
tmux setw window-status-activity-style none

tmux select-window -t 0
