prSections:
  - title: Pending Review
    filters: is:open -is:draft -reviewed-by:@me -author:@me -label:"Do not review" -label:"Do not merge"

  - title: Requested
    filters: is:open user-review-requested:@me

  - title: Reviewing
    filters: is:open commenter:@me

  - title: Open
    filters: is:open -is:draft

  - title: Mentioned
    filters: is:open mentions:@me

  - title: Mine
    filters: is:open author:@me

  - title: All
    filters: is:open

defaults:
  refetchIntervalMinutes: 30
  preview:
    open: false
    width: 80

  prsLimit: 20
  issuesLimit: 20
  view: prs

  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16

    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true

keybindings:
  issues: []
  prs: []

repoPaths: {}

theme:
  ui:
    table:
      showSeparator: true

pager:
  diff: ""
