#!/bin/bash

cd $BRAIN

todos_file="1-work/todos.md"

# Check if the file exists
if [ ! -f "$todos_file" ]; then
	touch "$todos_file"
	echo "# To-Do List\n\n" >"$todos_file"
fi

nvim -c "e $todos_file"
