#!/bin/bash

cd "$BRAIN" || exit 1 # Exit if the directory doesn't exist

notes_file="2-self/20-yt/notes.md"
timestamp="$(date +"%Y-%m-%d")"

# Check if the file exists
if [ ! -f "$notes_file" ]; then
	touch "$notes_file"

	{
		echo "# YouTube video notes"
		echo ""
		echo "## 'template'"
		echo ""
		echo "- Link: "
		echo "- Date: $timestamp"
		echo ""
	} >>"$notes_file"

	nvim -c "e $notes_file"
else
	# Open the notes_file with Nvim and duplicate the template
	nvim -c "e $notes_file" -c "normal 3gg^V6jyP7jww"
fi
