[[session]]
name = "current_up"
startup_command = "sesh_current_up"
path = "~/com.github/current_up"

[[session]]
name = "dotf"
path = "~/com.github/dotfiles"
startup_command = "sesh_vim"

[[session]]
name = "Brain"
path = "~/Documents/Notes"
startup_command = "sesh_brain"

[[session]]
name = "slides"
path = "~/com.github/slides"

